### ISSUE TITLE
Error while trying to push QR code button

### ISSUE THREAD

**Issue by drorya1** [abdelkader/vCardEditor#39]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
QRCoder.Exceptions.DataTooLongException: The given payload exceeds the maximum size of the QR code standard. The maximum size allowed for the choosen paramters (ECC level=L, EncodingMode=Byte) is 2953 byte.
   at QRCoder.QRCodeGenerator.GetVersion(Int32 length, EncodingMode encMode, ECCLevel eccLevel)
   at QRCoder.QRCodeGenerator.GenerateQrCode(String plainText, ECCLevel eccLevel, Boolean forceUtf8, Boolean utf8BOM, EciMode eciMode, Int32 requestedVersion)
   at vCardEditor.View.QRDialog.RenderQrCode(String code)
   at vCardEditor.View.QRDialog..ctor(String content)
   at vCardEditor.View.MainForm.DisplayQRCode(String content)
   at VCFEditor.Presenter.MainPresenter.ExportQRHandler(Object sender, EventArgs e)
   at vCardEditor.View.MainForm.tbsQR_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
vCardEditor
    Assembly Version: 0.5.3.0

**Comment by abdelkader** [comment]
You can see from the error message, that you reached the maximum size allowed to a QR Code. 

You can more info from 
https://stackoverflow.com/questions/11065415/how-much-data-information-can-we-save-store-in-a-qr-code
